"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from tirdad_sdk.types import BaseModel
from typing_extensions import TypedDict


class ActivateDraftSubscriptionRequestTypedDict(TypedDict):
    start_date: datetime
    r"""start_date is the new start date for the subscription when activating"""


class ActivateDraftSubscriptionRequest(BaseModel):
    start_date: datetime
    r"""start_date is the new start date for the subscription when activating"""
