"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addonassociationentitytype import AddonAssociationEntityType
from .addonstatus import AddonStatus
from .checkoutsessionresponse import (
    CheckoutSessionResponse,
    CheckoutSessionResponseTypedDict,
)
from .invoiceresponse import InvoiceResponse, InvoiceResponseTypedDict
from .status import Status
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class AddAddonToSubscriptionResponseTypedDict(TypedDict):
    addon_id: NotRequired[str]
    addon_status: NotRequired[AddonStatus]
    cancellation_reason: NotRequired[str]
    cancelled_at: NotRequired[datetime]
    checkout_session: NotRequired[CheckoutSessionResponseTypedDict]
    created_at: NotRequired[datetime]
    created_by: NotRequired[str]
    end_date: NotRequired[datetime]
    entity_id: NotRequired[str]
    entity_type: NotRequired[AddonAssociationEntityType]
    environment_id: NotRequired[str]
    id: NotRequired[str]
    invoice: NotRequired[InvoiceResponseTypedDict]
    metadata: NotRequired[Dict[str, Any]]
    start_date: NotRequired[datetime]
    status: NotRequired[Status]
    tenant_id: NotRequired[str]
    updated_at: NotRequired[datetime]
    updated_by: NotRequired[str]


class AddAddonToSubscriptionResponse(BaseModel):
    addon_id: Optional[str] = None

    addon_status: Optional[AddonStatus] = None

    cancellation_reason: Optional[str] = None

    cancelled_at: Optional[datetime] = None

    checkout_session: Optional[CheckoutSessionResponse] = None

    created_at: Optional[datetime] = None

    created_by: Optional[str] = None

    end_date: Optional[datetime] = None

    entity_id: Optional[str] = None

    entity_type: Optional[AddonAssociationEntityType] = None

    environment_id: Optional[str] = None

    id: Optional[str] = None

    invoice: Optional[InvoiceResponse] = None

    metadata: Optional[Dict[str, Any]] = None

    start_date: Optional[datetime] = None

    status: Optional[Status] = None

    tenant_id: Optional[str] = None

    updated_at: Optional[datetime] = None

    updated_by: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "addon_id",
                "addon_status",
                "cancellation_reason",
                "cancelled_at",
                "checkout_session",
                "created_at",
                "created_by",
                "end_date",
                "entity_id",
                "entity_type",
                "environment_id",
                "id",
                "invoice",
                "metadata",
                "start_date",
                "status",
                "tenant_id",
                "updated_at",
                "updated_by",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
