"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addoncadence import AddonCadence
from .prorationbehavior import ProrationBehavior
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AddAddonRefTypedDict(TypedDict):
    addon_id: NotRequired[str]
    association_id: NotRequired[str]
    cadence: NotRequired[AddonCadence]
    proration_behavior: NotRequired[ProrationBehavior]
    start_date: NotRequired[datetime]


class AddAddonRef(BaseModel):
    addon_id: Optional[str] = None

    association_id: Optional[str] = None

    cadence: Optional[AddonCadence] = None

    proration_behavior: Optional[ProrationBehavior] = None

    start_date: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "addon_id",
                "association_id",
                "cadence",
                "proration_behavior",
                "start_date",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
