"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addoncadence import AddonCadence
from .lineitemcommitmentconfig import (
    LineItemCommitmentConfig,
    LineItemCommitmentConfigTypedDict,
)
from .prorationbehavior import ProrationBehavior
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class AddAddonToSubscriptionRequestTypedDict(TypedDict):
    addon_id: str
    cadence: NotRequired[AddonCadence]
    line_item_commitments: NotRequired[Dict[str, LineItemCommitmentConfigTypedDict]]
    r"""LineItemCommitments allows setting commitment configuration per addon line item (keyed by price_id)"""
    metadata: NotRequired[Dict[str, Any]]
    proration_behavior: NotRequired[ProrationBehavior]
    start_date: NotRequired[datetime]


class AddAddonToSubscriptionRequest(BaseModel):
    addon_id: str

    cadence: Optional[AddonCadence] = None

    line_item_commitments: Optional[Dict[str, LineItemCommitmentConfig]] = None
    r"""LineItemCommitments allows setting commitment configuration per addon line item (keyed by price_id)"""

    metadata: Optional[Dict[str, Any]] = None

    proration_behavior: Optional[ProrationBehavior] = None

    start_date: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "cadence",
                "line_item_commitments",
                "metadata",
                "proration_behavior",
                "start_date",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
