"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AddLineItemRequestTypedDict(TypedDict):
    amount: str
    display_name: str
    quantity: str
    description: NotRequired[str]
    period_end: NotRequired[datetime]
    period_start: NotRequired[datetime]


class AddLineItemRequest(BaseModel):
    amount: str

    display_name: str

    quantity: str

    description: Optional[str] = None

    period_end: Optional[datetime] = None

    period_start: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "period_end", "period_start"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
