"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entitlementusageresetperiod import EntitlementUsageResetPeriod
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AggregatedEntitlementTypedDict(TypedDict):
    is_enabled: NotRequired[bool]
    is_soft_limit: NotRequired[bool]
    static_values: NotRequired[List[str]]
    r"""For static/SLA features"""
    usage_limit: NotRequired[int]
    usage_reset_period: NotRequired[EntitlementUsageResetPeriod]


class AggregatedEntitlement(BaseModel):
    is_enabled: Optional[bool] = None

    is_soft_limit: Optional[bool] = None

    static_values: Optional[List[str]] = None
    r"""For static/SLA features"""

    usage_limit: Optional[int] = None

    usage_reset_period: Optional[EntitlementUsageResetPeriod] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "is_enabled",
                "is_soft_limit",
                "static_values",
                "usage_limit",
                "usage_reset_period",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
