"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tirdad_sdk.types import UnrecognizedStr
from typing import Literal, Union


AlertType = Union[
    Literal[
        "low_ongoing_balance",
        "low_credit_balance",
        "feature_wallet_balance",
        "subscription_spend",
        "subscription_line_item_spend",
        "subscription_group_spend",
    ],
    UnrecognizedStr,
]
