"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .analytics_filter import AnalyticsFilter, AnalyticsFilterTypedDict
from .analytics_sortspec import AnalyticsSortSpec, AnalyticsSortSpecTypedDict
from .analytics_timespecraw import AnalyticsTimeSpecRaw, AnalyticsTimeSpecRawTypedDict
from .analytics_variable import AnalyticsVariable, AnalyticsVariableTypedDict
from .metric import Metric
from .shape import Shape
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AnalyticsViewDefinitionTypedDict(TypedDict):
    metrics: List[Metric]
    shape: Shape
    dimensions: NotRequired[List[str]]
    filters: NotRequired[List[AnalyticsFilterTypedDict]]
    limit: NotRequired[int]
    name: NotRequired[str]
    sort: NotRequired[List[AnalyticsSortSpecTypedDict]]
    time: NotRequired[AnalyticsTimeSpecRawTypedDict]
    variables: NotRequired[List[AnalyticsVariableTypedDict]]


class AnalyticsViewDefinition(BaseModel):
    metrics: List[Metric]

    shape: Shape

    dimensions: Optional[List[str]] = None

    filters: Optional[List[AnalyticsFilter]] = None

    limit: Optional[int] = None

    name: Optional[str] = None

    sort: Optional[List[AnalyticsSortSpec]] = None

    time: Optional[AnalyticsTimeSpecRaw] = None

    variables: Optional[List[AnalyticsVariable]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["dimensions", "filters", "limit", "name", "sort", "time", "variables"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
