"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .variabletype import VariableType
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AnalyticsVariableTypedDict(TypedDict):
    type: VariableType
    default: NotRequired[List[str]]
    name: NotRequired[str]
    required: NotRequired[bool]


class AnalyticsVariable(BaseModel):
    type: VariableType

    default: Optional[List[str]] = None

    name: Optional[str] = None

    required: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["default", "name", "required"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
