"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addonstatus import AddonStatus
from .changedaddonassociationaction import ChangedAddonAssociationAction
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ChangedAddonAssociationTypedDict(TypedDict):
    addon_id: NotRequired[str]
    addon_status: NotRequired[AddonStatus]
    change_action: NotRequired[ChangedAddonAssociationAction]
    r"""created | ended"""
    end_date: NotRequired[datetime]
    id: NotRequired[str]
    start_date: NotRequired[datetime]


class ChangedAddonAssociation(BaseModel):
    addon_id: Optional[str] = None

    addon_status: Optional[AddonStatus] = None

    change_action: Optional[ChangedAddonAssociationAction] = None
    r"""created | ended"""

    end_date: Optional[datetime] = None

    id: Optional[str] = None

    start_date: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "addon_id",
                "addon_status",
                "change_action",
                "end_date",
                "id",
                "start_date",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
