"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .changedinvoice import ChangedInvoice, ChangedInvoiceTypedDict
from .changedlineitem import ChangedLineItem, ChangedLineItemTypedDict
from .changedsubscription import ChangedSubscription, ChangedSubscriptionTypedDict
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ChangedResourcesTypedDict(TypedDict):
    invoices: NotRequired[List[ChangedInvoiceTypedDict]]
    line_items: NotRequired[List[ChangedLineItemTypedDict]]
    subscriptions: NotRequired[List[ChangedSubscriptionTypedDict]]


class ChangedResources(BaseModel):
    invoices: Optional[List[ChangedInvoice]] = None

    line_items: Optional[List[ChangedLineItem]] = None

    subscriptions: Optional[List[ChangedSubscription]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["invoices", "line_items", "subscriptions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
