"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .collectionmethod import CollectionMethod
from .paymentmethodtype import PaymentMethodType
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CheckoutPaymentProviderConfigTypedDict(TypedDict):
    collection_method: NotRequired[CollectionMethod]
    customer_not_present: NotRequired[bool]
    r"""CustomerNotPresent is the unattended/MIT opt-in. Zero value (omitted) means
    the customer is present, so a missed auto-charge may fall back to a hosted
    authorization link. Set true only from merchant-initiated paths (auto top-up).
    """
    max_mandate_limit: NotRequired[str]
    payment_method: NotRequired[PaymentMethodType]


class CheckoutPaymentProviderConfig(BaseModel):
    collection_method: Optional[CollectionMethod] = None

    customer_not_present: Optional[bool] = None
    r"""CustomerNotPresent is the unattended/MIT opt-in. Zero value (omitted) means
    the customer is present, so a missed auto-charge may fall back to a hosted
    authorization link. Set true only from merchant-initiated paths (auto top-up).
    """

    max_mandate_limit: Optional[str] = None

    payment_method: Optional[PaymentMethodType] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "collection_method",
                "customer_not_present",
                "max_mandate_limit",
                "payment_method",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
