"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tirdad_sdk.types import UnrecognizedStr
from typing import Literal, Union


CheckoutAction = Union[
    Literal[
        "create_subscription",
        "modify_subscription",
    ],
    UnrecognizedStr,
]
