"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addaddontosubscriptionrequest import (
    AddAddonToSubscriptionRequest,
    AddAddonToSubscriptionRequestTypedDict,
)
from .billingcycle import BillingCycle
from .billingperiod import BillingPeriod
from .collectionmethod import CollectionMethod
from .createcreditgrantrequest import (
    CreateCreditGrantRequest,
    CreateCreditGrantRequestTypedDict,
)
from .createsubscriptionlineitemrequest import (
    CreateSubscriptionLineItemRequest,
    CreateSubscriptionLineItemRequestTypedDict,
)
from .lineitemcommitmentconfig import (
    LineItemCommitmentConfig,
    LineItemCommitmentConfigTypedDict,
)
from .overrideentitlementrequest import (
    OverrideEntitlementRequest,
    OverrideEntitlementRequestTypedDict,
)
from .overridelineitemrequest import (
    OverrideLineItemRequest,
    OverrideLineItemRequestTypedDict,
)
from .paymentbehavior import PaymentBehavior
from .paymentterms import PaymentTerms
from .prorationbehavior import ProrationBehavior
from .subscriptioncouponinput import (
    SubscriptionCouponInput,
    SubscriptionCouponInputTypedDict,
)
from .subscriptioninheritanceconfig import (
    SubscriptionInheritanceConfig,
    SubscriptionInheritanceConfigTypedDict,
)
from .subscriptionphasecreaterequest import (
    SubscriptionPhaseCreateRequest,
    SubscriptionPhaseCreateRequestTypedDict,
)
from .subscriptionstatus import SubscriptionStatus
from .taxrateoverride import TaxRateOverride, TaxRateOverrideTypedDict
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class CreateSubscriptionRequestTypedDict(TypedDict):
    billing_period: BillingPeriod
    currency: str
    plan_id: str
    addons: NotRequired[List[AddAddonToSubscriptionRequestTypedDict]]
    auto_invoice_threshold: NotRequired[str]
    r"""AutoInvoiceThreshold triggers a mid-period invoice when usage (in subscription currency) exceeds this amount.
    Standalone subscriptions only; all plan prices must be usage-based. Immutable after creation.
    """
    billing_anchor: NotRequired[datetime]
    r"""BillingAnchor overrides the derived anchor for anniversary billing. For monthly billing,
    the day-of-month defines cycle boundaries (shorter first period if start is before that day).
    """
    billing_cycle: NotRequired[BillingCycle]
    billing_period_count: NotRequired[int]
    collection_method: NotRequired[CollectionMethod]
    commitment_amount: NotRequired[str]
    commitment_duration: NotRequired[BillingPeriod]
    coupons: NotRequired[List[str]]
    r"""Deprecated: use SubscriptionCoupons instead."""
    credit_grants: NotRequired[List[CreateCreditGrantRequestTypedDict]]
    customer_id: NotRequired[str]
    r"""CustomerID takes priority over ExternalCustomerID when both are provided."""
    enable_true_up: NotRequired[bool]
    end_date: NotRequired[datetime]
    external_customer_id: NotRequired[str]
    gateway_payment_method_id: NotRequired[str]
    inheritance: NotRequired[SubscriptionInheritanceConfigTypedDict]
    line_item_commitments: NotRequired[Dict[str, LineItemCommitmentConfigTypedDict]]
    r"""LineItemCommitments sets per-line-item commitment config, keyed by price_id."""
    line_item_coupons: NotRequired[Dict[str, List[str]]]
    r"""Deprecated: use SubscriptionCoupons instead."""
    line_items: NotRequired[List[CreateSubscriptionLineItemRequestTypedDict]]
    r"""LineItems are extra (non-plan) line items added at creation."""
    lookup_key: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    overage_factor: NotRequired[str]
    override_entitlements: NotRequired[List[OverrideEntitlementRequestTypedDict]]
    override_line_items: NotRequired[List[OverrideLineItemRequestTypedDict]]
    r"""OverrideLineItems overrides specific plan prices for this subscription."""
    payment_behavior: NotRequired[PaymentBehavior]
    payment_terms: NotRequired[PaymentTerms]
    phases: NotRequired[List[SubscriptionPhaseCreateRequestTypedDict]]
    proration_behavior: NotRequired[ProrationBehavior]
    start_date: NotRequired[datetime]
    subscription_coupons: NotRequired[List[SubscriptionCouponInputTypedDict]]
    r"""SubscriptionCoupons is the preferred way to attach coupons at creation.
    Accepts coupon_code; optionally targets a line item via price_id.
    """
    subscription_status: NotRequired[SubscriptionStatus]
    tax_rate_overrides: NotRequired[List[TaxRateOverrideTypedDict]]
    timezone: NotRequired[str]
    trial_period_days: NotRequired[int]
    r"""TrialPeriodDays: nil = inherit from plan prices, 0 = no trial, >0 = override in days."""


class CreateSubscriptionRequest(BaseModel):
    billing_period: BillingPeriod

    currency: str

    plan_id: str

    addons: Optional[List[AddAddonToSubscriptionRequest]] = None

    auto_invoice_threshold: Optional[str] = None
    r"""AutoInvoiceThreshold triggers a mid-period invoice when usage (in subscription currency) exceeds this amount.
    Standalone subscriptions only; all plan prices must be usage-based. Immutable after creation.
    """

    billing_anchor: Optional[datetime] = None
    r"""BillingAnchor overrides the derived anchor for anniversary billing. For monthly billing,
    the day-of-month defines cycle boundaries (shorter first period if start is before that day).
    """

    billing_cycle: Optional[BillingCycle] = None

    billing_period_count: Optional[int] = None

    collection_method: Optional[CollectionMethod] = None

    commitment_amount: Optional[str] = None

    commitment_duration: Optional[BillingPeriod] = None

    coupons: Optional[List[str]] = None
    r"""Deprecated: use SubscriptionCoupons instead."""

    credit_grants: Optional[List[CreateCreditGrantRequest]] = None

    customer_id: Optional[str] = None
    r"""CustomerID takes priority over ExternalCustomerID when both are provided."""

    enable_true_up: Optional[bool] = None

    end_date: Optional[datetime] = None

    external_customer_id: Optional[str] = None

    gateway_payment_method_id: Optional[str] = None

    inheritance: Optional[SubscriptionInheritanceConfig] = None

    line_item_commitments: Optional[Dict[str, LineItemCommitmentConfig]] = None
    r"""LineItemCommitments sets per-line-item commitment config, keyed by price_id."""

    line_item_coupons: Optional[Dict[str, List[str]]] = None
    r"""Deprecated: use SubscriptionCoupons instead."""

    line_items: Optional[List[CreateSubscriptionLineItemRequest]] = None
    r"""LineItems are extra (non-plan) line items added at creation."""

    lookup_key: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None

    overage_factor: Optional[str] = None

    override_entitlements: Optional[List[OverrideEntitlementRequest]] = None

    override_line_items: Optional[List[OverrideLineItemRequest]] = None
    r"""OverrideLineItems overrides specific plan prices for this subscription."""

    payment_behavior: Optional[PaymentBehavior] = None

    payment_terms: Optional[PaymentTerms] = None

    phases: Optional[List[SubscriptionPhaseCreateRequest]] = None

    proration_behavior: Optional[ProrationBehavior] = None

    start_date: Optional[datetime] = None

    subscription_coupons: Optional[List[SubscriptionCouponInput]] = None
    r"""SubscriptionCoupons is the preferred way to attach coupons at creation.
    Accepts coupon_code; optionally targets a line item via price_id.
    """

    subscription_status: Optional[SubscriptionStatus] = None

    tax_rate_overrides: Optional[List[TaxRateOverride]] = None

    timezone: Optional[str] = None

    trial_period_days: Optional[int] = None
    r"""TrialPeriodDays: nil = inherit from plan prices, 0 = no trial, >0 = override in days."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "addons",
                "auto_invoice_threshold",
                "billing_anchor",
                "billing_cycle",
                "billing_period_count",
                "collection_method",
                "commitment_amount",
                "commitment_duration",
                "coupons",
                "credit_grants",
                "customer_id",
                "enable_true_up",
                "end_date",
                "external_customer_id",
                "gateway_payment_method_id",
                "inheritance",
                "line_item_commitments",
                "line_item_coupons",
                "line_items",
                "lookup_key",
                "metadata",
                "overage_factor",
                "override_entitlements",
                "override_line_items",
                "payment_behavior",
                "payment_terms",
                "phases",
                "proration_behavior",
                "start_date",
                "subscription_coupons",
                "subscription_status",
                "tax_rate_overrides",
                "timezone",
                "trial_period_days",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
