"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .secrettype import SecretType
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateAPIKeyRequestTypedDict(TypedDict):
    name: str
    type: SecretType
    expires_at: NotRequired[datetime]
    service_account_id: NotRequired[str]


class CreateAPIKeyRequest(BaseModel):
    name: str

    type: SecretType

    expires_at: Optional[datetime] = None

    service_account_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["expires_at", "service_account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
