"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entitlementaggregationmode import EntitlementAggregationMode
from .entitlemententitytype import EntitlementEntityType
from .entitlementgrantallocationbehavior import EntitlementGrantAllocationBehavior
from .entitlementgrantdurationunit import EntitlementGrantDurationUnit
from .entitlementgrantmeasure import EntitlementGrantMeasure
from .entitlementusageresetperiod import EntitlementUsageResetPeriod
from .featuretype import FeatureType
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class CreateEntitlementRequestTypedDict(TypedDict):
    feature_id: str
    feature_type: FeatureType
    aggregation_mode: NotRequired[EntitlementAggregationMode]
    config_value: NotRequired[Dict[str, Any]]
    end_date: NotRequired[datetime]
    entity_id: NotRequired[str]
    entity_type: NotRequired[EntitlementEntityType]
    grant_allocation_behavior: NotRequired[EntitlementGrantAllocationBehavior]
    grant_duration_unit: NotRequired[EntitlementGrantDurationUnit]
    grant_duration_value: NotRequired[int]
    grant_measure: NotRequired[EntitlementGrantMeasure]
    grant_quota: NotRequired[str]
    is_enabled: NotRequired[bool]
    is_soft_limit: NotRequired[bool]
    parent_entitlement_id: NotRequired[str]
    plan_id: NotRequired[str]
    start_date: NotRequired[datetime]
    static_value: NotRequired[str]
    usage_limit: NotRequired[int]
    usage_reset_period: NotRequired[EntitlementUsageResetPeriod]


class CreateEntitlementRequest(BaseModel):
    feature_id: str

    feature_type: FeatureType

    aggregation_mode: Optional[EntitlementAggregationMode] = None

    config_value: Optional[Dict[str, Any]] = None

    end_date: Optional[datetime] = None

    entity_id: Optional[str] = None

    entity_type: Optional[EntitlementEntityType] = None

    grant_allocation_behavior: Optional[EntitlementGrantAllocationBehavior] = None

    grant_duration_unit: Optional[EntitlementGrantDurationUnit] = None

    grant_duration_value: Optional[int] = None

    grant_measure: Optional[EntitlementGrantMeasure] = None

    grant_quota: Optional[str] = None

    is_enabled: Optional[bool] = None

    is_soft_limit: Optional[bool] = None

    parent_entitlement_id: Optional[str] = None

    plan_id: Optional[str] = None

    start_date: Optional[datetime] = None

    static_value: Optional[str] = None

    usage_limit: Optional[int] = None

    usage_reset_period: Optional[EntitlementUsageResetPeriod] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "aggregation_mode",
                "config_value",
                "end_date",
                "entity_id",
                "entity_type",
                "grant_allocation_behavior",
                "grant_duration_unit",
                "grant_duration_value",
                "grant_measure",
                "grant_quota",
                "is_enabled",
                "is_soft_limit",
                "parent_entitlement_id",
                "plan_id",
                "start_date",
                "static_value",
                "usage_limit",
                "usage_reset_period",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
