"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filtercondition import FilterCondition, FilterConditionTypedDict
from .sortcondition import SortCondition, SortConditionTypedDict
from .status import Status
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


CustomerFilterOrder = Literal[
    "asc",
    "desc",
]


class CustomerFilterTypedDict(TypedDict):
    customer_ids: NotRequired[List[str]]
    email: NotRequired[str]
    end_time: NotRequired[datetime]
    expand: NotRequired[str]
    external_id: NotRequired[str]
    external_ids: NotRequired[List[str]]
    filters: NotRequired[List[FilterConditionTypedDict]]
    limit: NotRequired[int]
    metadata: NotRequired[Dict[str, str]]
    offset: NotRequired[int]
    order: NotRequired[CustomerFilterOrder]
    sort: NotRequired[List[SortConditionTypedDict]]
    start_time: NotRequired[datetime]
    status: NotRequired[Status]


class CustomerFilter(BaseModel):
    customer_ids: Optional[List[str]] = None

    email: Optional[str] = None

    end_time: Optional[datetime] = None

    expand: Optional[str] = None

    external_id: Optional[str] = None

    external_ids: Optional[List[str]] = None

    filters: Optional[List[FilterCondition]] = None

    limit: Optional[int] = None

    metadata: Optional[Dict[str, str]] = None

    offset: Optional[int] = None

    order: Optional[CustomerFilterOrder] = None

    sort: Optional[List[SortCondition]] = None

    start_time: Optional[datetime] = None

    status: Optional[Status] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "customer_ids",
                "email",
                "end_time",
                "expand",
                "external_id",
                "external_ids",
                "filters",
                "limit",
                "metadata",
                "offset",
                "order",
                "sort",
                "start_time",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
