"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customerlookupresult import CustomerLookupResult, CustomerLookupResultTypedDict
from .failurepoint import FailurePoint, FailurePointTypedDict
from .metermatchingresult import MeterMatchingResult, MeterMatchingResultTypedDict
from .pricelookupresult import PriceLookupResult, PriceLookupResultTypedDict
from .subscriptionlineitemlookupresult import (
    SubscriptionLineItemLookupResult,
    SubscriptionLineItemLookupResultTypedDict,
)
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DebugTrackerTypedDict(TypedDict):
    customer_lookup: NotRequired[CustomerLookupResultTypedDict]
    failure_point: NotRequired[FailurePointTypedDict]
    meter_matching: NotRequired[MeterMatchingResultTypedDict]
    price_lookup: NotRequired[PriceLookupResultTypedDict]
    subscription_line_item_lookup: NotRequired[
        SubscriptionLineItemLookupResultTypedDict
    ]


class DebugTracker(BaseModel):
    customer_lookup: Optional[CustomerLookupResult] = None

    failure_point: Optional[FailurePoint] = None

    meter_matching: Optional[MeterMatchingResult] = None

    price_lookup: Optional[PriceLookupResult] = None

    subscription_line_item_lookup: Optional[SubscriptionLineItemLookupResult] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "customer_lookup",
                "failure_point",
                "meter_matching",
                "price_lookup",
                "subscription_line_item_lookup",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
