"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DeleteCreditGrantRequestTypedDict(TypedDict):
    effective_date: NotRequired[datetime]
    r"""EffectiveDate is optional; when set (subscription scope) the grant end date is set to this time."""


class DeleteCreditGrantRequest(BaseModel):
    effective_date: Optional[datetime] = None
    r"""EffectiveDate is optional; when set (subscription scope) the grant end date is set to this time."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["effective_date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
