"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .integrationentitytype import IntegrationEntityType
from tirdad_sdk.types import BaseModel
from typing_extensions import TypedDict


class DelinkIntegrationMappingRequestTypedDict(TypedDict):
    entity_id: str
    entity_type: IntegrationEntityType
    provider_type: str


class DelinkIntegrationMappingRequest(BaseModel):
    entity_id: str

    entity_type: IntegrationEntityType

    provider_type: str
