"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entitlemententitytype import EntitlementEntityType
from .featuretype import FeatureType
from .filtercondition import FilterCondition, FilterConditionTypedDict
from .sortcondition import SortCondition, SortConditionTypedDict
from .status import Status
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


EntitlementFilterOrder = Literal[
    "asc",
    "desc",
]


class EntitlementFilterTypedDict(TypedDict):
    end_time: NotRequired[datetime]
    entity_ids: NotRequired[List[str]]
    entity_type: NotRequired[EntitlementEntityType]
    expand: NotRequired[str]
    feature_ids: NotRequired[List[str]]
    feature_type: NotRequired[FeatureType]
    filters: NotRequired[List[FilterConditionTypedDict]]
    r"""Specific filters for entitlements"""
    is_enabled: NotRequired[bool]
    limit: NotRequired[int]
    offset: NotRequired[int]
    order: NotRequired[EntitlementFilterOrder]
    plan_ids: NotRequired[List[str]]
    sort: NotRequired[List[SortConditionTypedDict]]
    start_time: NotRequired[datetime]
    status: NotRequired[Status]


class EntitlementFilter(BaseModel):
    end_time: Optional[datetime] = None

    entity_ids: Optional[List[str]] = None

    entity_type: Optional[EntitlementEntityType] = None

    expand: Optional[str] = None

    feature_ids: Optional[List[str]] = None

    feature_type: Optional[FeatureType] = None

    filters: Optional[List[FilterCondition]] = None
    r"""Specific filters for entitlements"""

    is_enabled: Optional[bool] = None

    limit: Optional[int] = None

    offset: Optional[int] = None

    order: Optional[EntitlementFilterOrder] = None

    plan_ids: Optional[List[str]] = None

    sort: Optional[List[SortCondition]] = None

    start_time: Optional[datetime] = None

    status: Optional[Status] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "end_time",
                "entity_ids",
                "entity_type",
                "expand",
                "feature_ids",
                "feature_type",
                "filters",
                "is_enabled",
                "limit",
                "offset",
                "order",
                "plan_ids",
                "sort",
                "start_time",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
