"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entitychangebehaviour import EntityChangeBehaviour
from .subscriptionlineitementitytype import SubscriptionLineItemEntityType
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class EntityChangeResultTypedDict(TypedDict):
    behaviour: NotRequired[EntityChangeBehaviour]
    entity_id: NotRequired[str]
    entity_type: NotRequired[SubscriptionLineItemEntityType]
    reference_id: NotRequired[str]


class EntityChangeResult(BaseModel):
    behaviour: Optional[EntityChangeBehaviour] = None

    entity_id: Optional[str] = None

    entity_type: Optional[SubscriptionLineItemEntityType] = None

    reference_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["behaviour", "entity_id", "entity_type", "reference_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
