"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errorcode import ErrorCode
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ErrorResponseTypedDict(TypedDict):
    code: NotRequired[ErrorCode]
    http_status_code: NotRequired[int]
    message: NotRequired[str]


class ErrorResponse(BaseModel):
    code: Optional[ErrorCode] = None

    http_status_code: Optional[int] = None

    message: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["code", "http_status_code", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
