"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tirdad_sdk.types import BaseModel
from tirdad_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetPriceUnitByCodeRequestTypedDict(TypedDict):
    code: str
    r"""Price unit code"""


class GetPriceUnitByCodeRequest(BaseModel):
    code: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Price unit code"""
