"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customanalyticitem import CustomAnalyticItem, CustomAnalyticItemTypedDict
from .usageanalyticitem import UsageAnalyticItem, UsageAnalyticItemTypedDict
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GetUsageAnalyticsResponseTypedDict(TypedDict):
    currency: NotRequired[str]
    custom_analytics: NotRequired[List[CustomAnalyticItemTypedDict]]
    items: NotRequired[List[UsageAnalyticItemTypedDict]]
    total_cost: NotRequired[str]


class GetUsageAnalyticsResponse(BaseModel):
    currency: Optional[str] = None

    custom_analytics: Optional[List[CustomAnalyticItem]] = None

    items: Optional[List[UsageAnalyticItem]] = None

    total_cost: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["currency", "custom_analytics", "items", "total_cost"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
