"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addaddontosubscriptionrequest import (
    AddAddonToSubscriptionRequest,
    AddAddonToSubscriptionRequestTypedDict,
)
from .billingperiod import BillingPeriod
from .createcreditgrantrequest import (
    CreateCreditGrantRequest,
    CreateCreditGrantRequestTypedDict,
)
from .createsubscriptionlineitemrequest import (
    CreateSubscriptionLineItemRequest,
    CreateSubscriptionLineItemRequestTypedDict,
)
from .lineitemcommitmentconfig import (
    LineItemCommitmentConfig,
    LineItemCommitmentConfigTypedDict,
)
from .overrideentitlementrequest import (
    OverrideEntitlementRequest,
    OverrideEntitlementRequestTypedDict,
)
from .overridelineitemrequest import (
    OverrideLineItemRequest,
    OverrideLineItemRequestTypedDict,
)
from .subscriptioncouponinput import (
    SubscriptionCouponInput,
    SubscriptionCouponInputTypedDict,
)
from .subscriptionphasecreaterequest import (
    SubscriptionPhaseCreateRequest,
    SubscriptionPhaseCreateRequestTypedDict,
)
from .taxrateoverride import TaxRateOverride, TaxRateOverrideTypedDict
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class GroupedInvoicingChildRequestTypedDict(TypedDict):
    external_customer_id: str
    plan_id: str
    addons: NotRequired[List[AddAddonToSubscriptionRequestTypedDict]]
    commitment_amount: NotRequired[str]
    commitment_duration: NotRequired[BillingPeriod]
    coupons: NotRequired[List[str]]
    r"""Deprecated: use SubscriptionCoupons instead."""
    credit_grants: NotRequired[List[CreateCreditGrantRequestTypedDict]]
    enable_true_up: NotRequired[bool]
    line_item_commitments: NotRequired[Dict[str, LineItemCommitmentConfigTypedDict]]
    r"""LineItemCommitments sets per-line-item commitment config, keyed by price_id."""
    line_item_coupons: NotRequired[Dict[str, List[str]]]
    r"""Deprecated: use SubscriptionCoupons instead."""
    line_items: NotRequired[List[CreateSubscriptionLineItemRequestTypedDict]]
    r"""LineItems are extra (non-plan) line items added at creation."""
    overage_factor: NotRequired[str]
    override_entitlements: NotRequired[List[OverrideEntitlementRequestTypedDict]]
    override_line_items: NotRequired[List[OverrideLineItemRequestTypedDict]]
    r"""OverrideLineItems overrides specific plan prices for this subscription."""
    phases: NotRequired[List[SubscriptionPhaseCreateRequestTypedDict]]
    subscription_coupons: NotRequired[List[SubscriptionCouponInputTypedDict]]
    r"""SubscriptionCoupons is the preferred way to attach coupons at creation.
    Accepts coupon_code; optionally targets a line item via price_id.
    """
    tax_rate_overrides: NotRequired[List[TaxRateOverrideTypedDict]]
    trial_period_days: NotRequired[int]
    r"""TrialPeriodDays: nil = inherit from plan prices, 0 = no trial, >0 = override in days."""


class GroupedInvoicingChildRequest(BaseModel):
    external_customer_id: str

    plan_id: str

    addons: Optional[List[AddAddonToSubscriptionRequest]] = None

    commitment_amount: Optional[str] = None

    commitment_duration: Optional[BillingPeriod] = None

    coupons: Optional[List[str]] = None
    r"""Deprecated: use SubscriptionCoupons instead."""

    credit_grants: Optional[List[CreateCreditGrantRequest]] = None

    enable_true_up: Optional[bool] = None

    line_item_commitments: Optional[Dict[str, LineItemCommitmentConfig]] = None
    r"""LineItemCommitments sets per-line-item commitment config, keyed by price_id."""

    line_item_coupons: Optional[Dict[str, List[str]]] = None
    r"""Deprecated: use SubscriptionCoupons instead."""

    line_items: Optional[List[CreateSubscriptionLineItemRequest]] = None
    r"""LineItems are extra (non-plan) line items added at creation."""

    overage_factor: Optional[str] = None

    override_entitlements: Optional[List[OverrideEntitlementRequest]] = None

    override_line_items: Optional[List[OverrideLineItemRequest]] = None
    r"""OverrideLineItems overrides specific plan prices for this subscription."""

    phases: Optional[List[SubscriptionPhaseCreateRequest]] = None

    subscription_coupons: Optional[List[SubscriptionCouponInput]] = None
    r"""SubscriptionCoupons is the preferred way to attach coupons at creation.
    Accepts coupon_code; optionally targets a line item via price_id.
    """

    tax_rate_overrides: Optional[List[TaxRateOverride]] = None

    trial_period_days: Optional[int] = None
    r"""TrialPeriodDays: nil = inherit from plan prices, 0 = no trial, >0 = override in days."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "addons",
                "commitment_amount",
                "commitment_duration",
                "coupons",
                "credit_grants",
                "enable_true_up",
                "line_item_commitments",
                "line_item_coupons",
                "line_items",
                "overage_factor",
                "override_entitlements",
                "override_line_items",
                "phases",
                "subscription_coupons",
                "tax_rate_overrides",
                "trial_period_days",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
