"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filtercondition import FilterCondition, FilterConditionTypedDict
from .sortcondition import SortCondition, SortConditionTypedDict
from .status import Status
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


GroupFilterOrder = Literal[
    "asc",
    "desc",
]


class GroupFilterTypedDict(TypedDict):
    end_time: NotRequired[datetime]
    entity_type: NotRequired[str]
    expand: NotRequired[str]
    filters: NotRequired[List[FilterConditionTypedDict]]
    r"""filters allows complex filtering based on multiple fields"""
    group_ids: NotRequired[List[str]]
    r"""Group specific filters"""
    limit: NotRequired[int]
    lookup_key: NotRequired[str]
    name: NotRequired[str]
    offset: NotRequired[int]
    order: NotRequired[GroupFilterOrder]
    sort: NotRequired[List[SortConditionTypedDict]]
    start_time: NotRequired[datetime]
    status: NotRequired[Status]


class GroupFilter(BaseModel):
    end_time: Optional[datetime] = None

    entity_type: Optional[str] = None

    expand: Optional[str] = None

    filters: Optional[List[FilterCondition]] = None
    r"""filters allows complex filtering based on multiple fields"""

    group_ids: Optional[List[str]] = None
    r"""Group specific filters"""

    limit: Optional[int] = None

    lookup_key: Optional[str] = None

    name: Optional[str] = None

    offset: Optional[int] = None

    order: Optional[GroupFilterOrder] = None

    sort: Optional[List[SortCondition]] = None

    start_time: Optional[datetime] = None

    status: Optional[Status] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "end_time",
                "entity_type",
                "expand",
                "filters",
                "group_ids",
                "limit",
                "lookup_key",
                "name",
                "offset",
                "order",
                "sort",
                "start_time",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
