"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tirdad_sdk.types import UnrecognizedStr
from typing import Literal, Union


LineItemGrouping = Union[
    Literal[
        "per_charge_period",
        "per_billing_period",
    ],
    UnrecognizedStr,
]
