"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from tirdad_sdk.utils import FieldMetadata, QueryParamMetadata
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ListRbacRolesUserType = Literal[
    "user",
    "service_account",
]
r"""Filter by user type"""


class ListRbacRolesRequestTypedDict(TypedDict):
    user_type: NotRequired[ListRbacRolesUserType]
    r"""Filter by user type"""


class ListRbacRolesRequest(BaseModel):
    user_type: Annotated[
        Optional[ListRbacRolesUserType],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by user type"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["user_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
