"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from tirdad_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListCustomerPaymentMethodsRequestTypedDict(TypedDict):
    id: str
    r"""Customer ID"""
    providers: NotRequired[List[str]]
    r"""Limit to these payment gateways"""


class ListCustomerPaymentMethodsRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Customer ID"""

    providers: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Limit to these payment gateways"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["providers"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
