"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .creditgrantapplicationresponse import (
    CreditGrantApplicationResponse,
    CreditGrantApplicationResponseTypedDict,
)
from .paginationresponse import PaginationResponse, PaginationResponseTypedDict
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListCreditGrantApplicationsResponseTypedDict(TypedDict):
    items: NotRequired[List[CreditGrantApplicationResponseTypedDict]]
    pagination: NotRequired[PaginationResponseTypedDict]


class ListCreditGrantApplicationsResponse(BaseModel):
    items: Optional[List[CreditGrantApplicationResponse]] = None

    pagination: Optional[PaginationResponse] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["items", "pagination"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
