"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .billingperiodbehaviour import BillingPeriodBehaviour
from .subscriptionchangeentitypolicies import (
    SubscriptionChangeEntityPolicies,
    SubscriptionChangeEntityPoliciesTypedDict,
)
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PlanChangeScheduleDetailsTypedDict(TypedDict):
    billing_period_behaviour: NotRequired[BillingPeriodBehaviour]
    entity_policies: NotRequired[SubscriptionChangeEntityPoliciesTypedDict]
    target_plan_id: NotRequired[str]


class PlanChangeScheduleDetails(BaseModel):
    billing_period_behaviour: Optional[BillingPeriodBehaviour] = None

    entity_policies: Optional[SubscriptionChangeEntityPolicies] = None

    target_plan_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["billing_period_behaviour", "entity_policies", "target_plan_id"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
