"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .status import Status
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class PriceUnitResponseTypedDict(TypedDict):
    base_currency: NotRequired[str]
    code: NotRequired[str]
    conversion_rate: NotRequired[str]
    created_at: NotRequired[datetime]
    created_by: NotRequired[str]
    environment_id: NotRequired[str]
    id: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    name: NotRequired[str]
    status: NotRequired[Status]
    symbol: NotRequired[str]
    tenant_id: NotRequired[str]
    updated_at: NotRequired[datetime]
    updated_by: NotRequired[str]


class PriceUnitResponse(BaseModel):
    base_currency: Optional[str] = None

    code: Optional[str] = None

    conversion_rate: Optional[str] = None

    created_at: Optional[datetime] = None

    created_by: Optional[str] = None

    environment_id: Optional[str] = None

    id: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None

    name: Optional[str] = None

    status: Optional[Status] = None

    symbol: Optional[str] = None

    tenant_id: Optional[str] = None

    updated_at: Optional[datetime] = None

    updated_by: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "base_currency",
                "code",
                "conversion_rate",
                "created_at",
                "created_by",
                "environment_id",
                "id",
                "metadata",
                "name",
                "status",
                "symbol",
                "tenant_id",
                "updated_at",
                "updated_by",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
