"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .paymentgatewaytype import PaymentGatewayType
from .providererror import ProviderError, ProviderErrorTypedDict
from .savedpaymentmethod import SavedPaymentMethod, SavedPaymentMethodTypedDict
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ProviderSavedPaymentMethodsTypedDict(TypedDict):
    error: NotRequired[ProviderErrorTypedDict]
    items: NotRequired[List[SavedPaymentMethodTypedDict]]
    provider: NotRequired[PaymentGatewayType]


class ProviderSavedPaymentMethods(BaseModel):
    error: Optional[ProviderError] = None

    items: Optional[List[SavedPaymentMethod]] = None

    provider: Optional[PaymentGatewayType] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["error", "items", "provider"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
