"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tirdad_sdk.types import UnrecognizedStr
from typing import Literal, Union


RefundDestination = Union[
    Literal[
        "GATEWAY",
        "WALLET",
        "OUT_OF_BAND",
    ],
    UnrecognizedStr,
]
