"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


RefundTarget = Literal[
    "PREPAID_WALLET",
    "BACK_TO_SOURCE",
]
