"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .prorationbehavior import ProrationBehavior
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RemoveAddonRequestTypedDict(TypedDict):
    addon_association_id: str
    effective_date: NotRequired[datetime]
    r"""EffectiveDate is the date the cancellation takes effect.
    When nil the addon is cancelled at the end of the current period.
    When provided it must fall within [CurrentPeriodStart, CurrentPeriodEnd]; mid-period
    values combined with create_prorations will issue a wallet credit for unused time.
    """
    proration_behavior: NotRequired[ProrationBehavior]
    reason: NotRequired[str]


class RemoveAddonRequest(BaseModel):
    addon_association_id: str

    effective_date: Optional[datetime] = None
    r"""EffectiveDate is the date the cancellation takes effect.
    When nil the addon is cancelled at the end of the current period.
    When provided it must fall within [CurrentPeriodStart, CurrentPeriodEnd]; mid-period
    values combined with create_prorations will issue a wallet credit for unused time.
    """

    proration_behavior: Optional[ProrationBehavior] = None

    reason: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["effective_date", "proration_behavior", "reason"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
