"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .revenueanalyticsrequest import (
    RevenueAnalyticsRequest,
    RevenueAnalyticsRequestTypedDict,
)
from .revenueanalyticsrow import RevenueAnalyticsRow, RevenueAnalyticsRowTypedDict
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RevenueAnalyticsResponseTypedDict(TypedDict):
    contains_allocated: NotRequired[bool]
    r"""ContainsAllocated is true when any bucket includes whole-period amounts
    spread across days (amortized) or booked on a single day (billed) —
    i.e. the day view carries period-shaped charges, not only true daily
    accruals.
    """
    query: NotRequired[RevenueAnalyticsRequestTypedDict]
    rows: NotRequired[List[RevenueAnalyticsRowTypedDict]]


class RevenueAnalyticsResponse(BaseModel):
    contains_allocated: Optional[bool] = None
    r"""ContainsAllocated is true when any bucket includes whole-period amounts
    spread across days (amortized) or booked on a single day (billed) —
    i.e. the day view carries period-shaped charges, not only true daily
    accruals.
    """

    query: Optional[RevenueAnalyticsRequest] = None

    rows: Optional[List[RevenueAnalyticsRow]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contains_allocated", "query", "rows"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
