"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .paymentgatewaytype import PaymentGatewayType
from .paymentmethodstatus import PaymentMethodStatus
from .paymentmethodtype import PaymentMethodType
from .savedcarddetails import SavedCardDetails, SavedCardDetailsTypedDict
from .savedrecurringpaymentdetails import (
    SavedRecurringPaymentDetails,
    SavedRecurringPaymentDetailsTypedDict,
)
from .savedupidetails import SavedUPIDetails, SavedUPIDetailsTypedDict
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SavedPaymentMethodTypedDict(TypedDict):
    can_auto_charge: NotRequired[bool]
    r"""Capability, not permission: could this be charged with nobody present.
    True for any active Chargebee or Stripe card (both vault off-session by
    construction); false for a Razorpay token without a mandate.
    """
    card: NotRequired[SavedCardDetailsTypedDict]
    id: NotRequired[str]
    instantly_chargeable: NotRequired[bool]
    is_default: NotRequired[bool]
    r"""Which method to use when several are saved at this provider.
    Scoped to the provider: two providers means two defaults.
    """
    provider: NotRequired[PaymentGatewayType]
    recurring: NotRequired[SavedRecurringPaymentDetailsTypedDict]
    status: NotRequired[PaymentMethodStatus]
    type: NotRequired[PaymentMethodType]
    upi: NotRequired[SavedUPIDetailsTypedDict]


class SavedPaymentMethod(BaseModel):
    can_auto_charge: Optional[bool] = None
    r"""Capability, not permission: could this be charged with nobody present.
    True for any active Chargebee or Stripe card (both vault off-session by
    construction); false for a Razorpay token without a mandate.
    """

    card: Optional[SavedCardDetails] = None

    id: Optional[str] = None

    instantly_chargeable: Optional[bool] = None

    is_default: Optional[bool] = None
    r"""Which method to use when several are saved at this provider.
    Scoped to the provider: two providers means two defaults.
    """

    provider: Optional[PaymentGatewayType] = None

    recurring: Optional[SavedRecurringPaymentDetails] = None

    status: Optional[PaymentMethodStatus] = None

    type: Optional[PaymentMethodType] = None

    upi: Optional[SavedUPIDetails] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "can_auto_charge",
                "card",
                "id",
                "instantly_chargeable",
                "is_default",
                "provider",
                "recurring",
                "status",
                "type",
                "upi",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
