"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .providersavedpaymentmethods import (
    ProviderSavedPaymentMethods,
    ProviderSavedPaymentMethodsTypedDict,
)
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SavedPaymentMethodsResponseTypedDict(TypedDict):
    providers: NotRequired[List[ProviderSavedPaymentMethodsTypedDict]]


class SavedPaymentMethodsResponse(BaseModel):
    providers: Optional[List[ProviderSavedPaymentMethods]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["providers"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
