"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .inheritanceaction import InheritanceAction
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SubModifyInheritanceRequestTypedDict(TypedDict):
    action: NotRequired[InheritanceAction]
    external_customer_ids_to_inherit_subscription: NotRequired[List[str]]
    r"""ExternalCustomerIDsToInheritSubscription is used for action=\"add\"."""
    external_customer_ids_to_remove: NotRequired[List[str]]
    r"""ExternalCustomerIDsToRemove is used for action=\"remove\"."""


class SubModifyInheritanceRequest(BaseModel):
    action: Optional[InheritanceAction] = None

    external_customer_ids_to_inherit_subscription: Optional[List[str]] = None
    r"""ExternalCustomerIDsToInheritSubscription is used for action=\"add\"."""

    external_customer_ids_to_remove: Optional[List[str]] = None
    r"""ExternalCustomerIDsToRemove is used for action=\"remove\"."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "action",
                "external_customer_ids_to_inherit_subscription",
                "external_customer_ids_to_remove",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
