"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .submodifycouponaction import SubModifyCouponAction
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SubModifyCouponParamsTypedDict(TypedDict):
    action: SubModifyCouponAction
    coupon_association_id: NotRequired[str]
    r"""Required when action=\"remove\". ID of the CouponAssociation to soft-delete."""
    coupon_code: NotRequired[str]
    r"""Required for action=\"add\". Coupon code of the coupon to attach."""
    end_date: NotRequired[datetime]
    r"""Optional. When the coupon association ends."""
    start_date: NotRequired[datetime]
    r"""Optional. When the coupon association starts; defaults to now."""
    subscription_id: NotRequired[str]
    r"""Optional. Apply at subscription level. Mutually exclusive with SubscriptionLineItemID."""
    subscription_line_item_id: NotRequired[str]
    r"""Optional. Apply at a specific line item. Mutually exclusive with SubscriptionID."""


class SubModifyCouponParams(BaseModel):
    action: SubModifyCouponAction

    coupon_association_id: Optional[str] = None
    r"""Required when action=\"remove\". ID of the CouponAssociation to soft-delete."""

    coupon_code: Optional[str] = None
    r"""Required for action=\"add\". Coupon code of the coupon to attach."""

    end_date: Optional[datetime] = None
    r"""Optional. When the coupon association ends."""

    start_date: Optional[datetime] = None
    r"""Optional. When the coupon association starts; defaults to now."""

    subscription_id: Optional[str] = None
    r"""Optional. Apply at subscription level. Mutually exclusive with SubscriptionLineItemID."""

    subscription_line_item_id: Optional[str] = None
    r"""Optional. Apply at a specific line item. Mutually exclusive with SubscriptionID."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "coupon_association_id",
                "coupon_code",
                "end_date",
                "start_date",
                "subscription_id",
                "subscription_line_item_id",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
