"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .lineitemquantitychange import (
    LineItemQuantityChange,
    LineItemQuantityChangeTypedDict,
)
from tirdad_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class SubModifyQuantityChangeRequestTypedDict(TypedDict):
    line_items: List[LineItemQuantityChangeTypedDict]


class SubModifyQuantityChangeRequest(BaseModel):
    line_items: List[LineItemQuantityChange]
