"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .prorationbehavior import ProrationBehavior
from .subscriptionchangeentitypolicies import (
    SubscriptionChangeEntityPolicies,
    SubscriptionChangeEntityPoliciesTypedDict,
)
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class SubscriptionChangeV2RequestTypedDict(TypedDict):
    proration_behavior: ProrationBehavior
    target_plan_id: str
    entity_policies: NotRequired[SubscriptionChangeEntityPoliciesTypedDict]
    idempotency_key: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]


class SubscriptionChangeV2Request(BaseModel):
    proration_behavior: ProrationBehavior

    target_plan_id: str

    entity_policies: Optional[SubscriptionChangeEntityPolicies] = None

    idempotency_key: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["entity_policies", "idempotency_key", "metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
