"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .billingmodel import BillingModel
from .billingperiod import BillingPeriod
from .billingtier import BillingTier
from .createpricetier import CreatePriceTier, CreatePriceTierTypedDict
from .invoicecadence import InvoiceCadence
from .price_transformquantity import (
    PriceTransformQuantity,
    PriceTransformQuantityTypedDict,
)
from .pricetype import PriceType
from .priceunitconfig import PriceUnitConfig, PriceUnitConfigTypedDict
from .priceunittype import PriceUnitType
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class SubscriptionPriceCreateRequestTypedDict(TypedDict):
    billing_model: BillingModel
    billing_period: BillingPeriod
    invoice_cadence: InvoiceCadence
    price_unit_type: PriceUnitType
    type: PriceType
    amount: NotRequired[str]
    billing_period_count: NotRequired[int]
    description: NotRequired[str]
    display_name: NotRequired[str]
    end_date: NotRequired[datetime]
    filter_values: NotRequired[Dict[str, List[str]]]
    lookup_key: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    meter_id: NotRequired[str]
    min_quantity: NotRequired[int]
    price_unit_config: NotRequired[PriceUnitConfigTypedDict]
    start_date: NotRequired[datetime]
    tier_mode: NotRequired[BillingTier]
    tiers: NotRequired[List[CreatePriceTierTypedDict]]
    transform_quantity: NotRequired[PriceTransformQuantityTypedDict]
    trial_period_days: NotRequired[int]


class SubscriptionPriceCreateRequest(BaseModel):
    billing_model: BillingModel

    billing_period: BillingPeriod

    invoice_cadence: InvoiceCadence

    price_unit_type: PriceUnitType

    type: PriceType

    amount: Optional[str] = None

    billing_period_count: Optional[int] = None

    description: Optional[str] = None

    display_name: Optional[str] = None

    end_date: Optional[datetime] = None

    filter_values: Optional[Dict[str, List[str]]] = None

    lookup_key: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None

    meter_id: Optional[str] = None

    min_quantity: Optional[int] = None

    price_unit_config: Optional[PriceUnitConfig] = None

    start_date: Optional[datetime] = None

    tier_mode: Optional[BillingTier] = None

    tiers: Optional[List[CreatePriceTier]] = None

    transform_quantity: Optional[PriceTransformQuantity] = None

    trial_period_days: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "amount",
                "billing_period_count",
                "description",
                "display_name",
                "end_date",
                "filter_values",
                "lookup_key",
                "metadata",
                "meter_id",
                "min_quantity",
                "price_unit_config",
                "start_date",
                "tier_mode",
                "tiers",
                "transform_quantity",
                "trial_period_days",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
