"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class UpdateFXRateRequestTypedDict(TypedDict):
    end_date: NotRequired[datetime]
    metadata: NotRequired[Dict[str, str]]
    rate: NotRequired[str]
    start_date: NotRequired[datetime]


class UpdateFXRateRequest(BaseModel):
    end_date: Optional[datetime] = None

    metadata: Optional[Dict[str, str]] = None

    rate: Optional[str] = None

    start_date: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["end_date", "metadata", "rate", "start_date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
