"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateaddonrequest import UpdateAddonRequest, UpdateAddonRequestTypedDict
from tirdad_sdk.types import BaseModel
from tirdad_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateAddonRequestRequestTypedDict(TypedDict):
    id: str
    r"""Addon ID"""
    body: UpdateAddonRequestTypedDict
    r"""Update Addon Request"""


class UpdateAddonRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Addon ID"""

    body: Annotated[
        UpdateAddonRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Update Addon Request"""
