"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateplanrequest import UpdatePlanRequest, UpdatePlanRequestTypedDict
from tirdad_sdk.types import BaseModel
from tirdad_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdatePlanRequestRequestTypedDict(TypedDict):
    id: str
    r"""Plan ID"""
    body: UpdatePlanRequestTypedDict
    r"""Plan update"""


class UpdatePlanRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Plan ID"""

    body: Annotated[
        UpdatePlanRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Plan update"""
