"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateuserrolesrequest import (
    UpdateUserRolesRequest,
    UpdateUserRolesRequestTypedDict,
)
from tirdad_sdk.types import BaseModel
from tirdad_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateUserRolesRequestRequestTypedDict(TypedDict):
    id: str
    r"""User ID"""
    body: UpdateUserRolesRequestTypedDict
    r"""Update user roles request"""


class UpdateUserRolesRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""User ID"""

    body: Annotated[
        UpdateUserRolesRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Update user roles request"""
