"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alertsettings import AlertSettings, AlertSettingsTypedDict
from tirdad_sdk.types import BaseModel
from typing_extensions import TypedDict


class UpdateAlertSettingsRequestTypedDict(TypedDict):
    config: AlertSettingsTypedDict


class UpdateAlertSettingsRequest(BaseModel):
    config: AlertSettings
