"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatetaxraterequest import UpdateTaxRateRequest, UpdateTaxRateRequestTypedDict
from tirdad_sdk.types import BaseModel
from tirdad_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateTaxRateRequestRequestTypedDict(TypedDict):
    id: str
    r"""Tax rate ID"""
    body: UpdateTaxRateRequestTypedDict
    r"""Tax rate to update"""


class UpdateTaxRateRequestRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Tax rate ID"""

    body: Annotated[
        UpdateTaxRateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Tax rate to update"""
