"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addon import Addon, AddonTypedDict
from .aggregationtype import AggregationType
from .bucketsummary import BucketSummary, BucketSummaryTypedDict
from .commitmentinfo import CommitmentInfo, CommitmentInfoTypedDict
from .feature import Feature, FeatureTypedDict
from .group_group import GroupGroup, GroupGroupTypedDict
from .meter_meter import MeterMeter, MeterMeterTypedDict
from .plan import Plan, PlanTypedDict
from .priceresponse import PriceResponse, PriceResponseTypedDict
from .reportingunit import ReportingUnit, ReportingUnitTypedDict
from .subscription_subscriptionlineitem import (
    SubscriptionSubscriptionLineItem,
    SubscriptionSubscriptionLineItemTypedDict,
)
from .usageanalyticpoint import UsageAnalyticPoint, UsageAnalyticPointTypedDict
from .windowsize import WindowSize
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class UsageAnalyticItemTypedDict(TypedDict):
    add_on_id: NotRequired[str]
    addon: NotRequired[AddonTypedDict]
    aggregation_type: NotRequired[AggregationType]
    bucket_summaries: NotRequired[List[BucketSummaryTypedDict]]
    r"""BucketSummaries is populated only when BreakdownBucket=true. Contains one
    entry per defined CommitmentTimeBucket plus one for out-of-bucket usage.
    """
    commitment_info: NotRequired[CommitmentInfoTypedDict]
    currency: NotRequired[str]
    event_count: NotRequired[int]
    r"""Number of events that contributed to this aggregation"""
    event_name: NotRequired[str]
    feature: NotRequired[FeatureTypedDict]
    feature_id: NotRequired[str]
    group: NotRequired[GroupGroupTypedDict]
    meter: NotRequired[MeterMeterTypedDict]
    meter_id: NotRequired[str]
    r"""Meter ID"""
    name: NotRequired[str]
    plan: NotRequired[PlanTypedDict]
    plan_id: NotRequired[str]
    points: NotRequired[List[UsageAnalyticPointTypedDict]]
    price: NotRequired[PriceResponseTypedDict]
    price_id: NotRequired[str]
    r"""Price ID used for this usage"""
    properties: NotRequired[Dict[str, str]]
    r"""Stores property values for flexible grouping (e.g., org_id -> \"org123\")"""
    reporting_unit: NotRequired[ReportingUnitTypedDict]
    source: NotRequired[str]
    sources: NotRequired[List[str]]
    r"""List of sources when not grouping by source"""
    sub_line_item_id: NotRequired[str]
    r"""Subscription line item ID"""
    subscription_id: NotRequired[str]
    r"""Subscription ID"""
    subscription_line_item: NotRequired[SubscriptionSubscriptionLineItemTypedDict]
    subtotal: NotRequired[str]
    total_cost: NotRequired[str]
    r"""TotalCost is the final cost after discount (Subtotal - TotalDiscount)"""
    total_discount: NotRequired[str]
    total_usage: NotRequired[str]
    total_usage_display: NotRequired[str]
    r"""Empty string when feature has no reporting unit; otherwise the value in reporting units"""
    unit: NotRequired[str]
    unit_plural: NotRequired[str]
    window_size: NotRequired[WindowSize]


class UsageAnalyticItem(BaseModel):
    add_on_id: Optional[str] = None

    addon: Optional[Addon] = None

    aggregation_type: Optional[AggregationType] = None

    bucket_summaries: Optional[List[BucketSummary]] = None
    r"""BucketSummaries is populated only when BreakdownBucket=true. Contains one
    entry per defined CommitmentTimeBucket plus one for out-of-bucket usage.
    """

    commitment_info: Optional[CommitmentInfo] = None

    currency: Optional[str] = None

    event_count: Optional[int] = None
    r"""Number of events that contributed to this aggregation"""

    event_name: Optional[str] = None

    feature: Optional[Feature] = None

    feature_id: Optional[str] = None

    group: Optional[GroupGroup] = None

    meter: Optional[MeterMeter] = None

    meter_id: Optional[str] = None
    r"""Meter ID"""

    name: Optional[str] = None

    plan: Optional[Plan] = None

    plan_id: Optional[str] = None

    points: Optional[List[UsageAnalyticPoint]] = None

    price: Optional[PriceResponse] = None

    price_id: Optional[str] = None
    r"""Price ID used for this usage"""

    properties: Optional[Dict[str, str]] = None
    r"""Stores property values for flexible grouping (e.g., org_id -> \"org123\")"""

    reporting_unit: Optional[ReportingUnit] = None

    source: Optional[str] = None

    sources: Optional[List[str]] = None
    r"""List of sources when not grouping by source"""

    sub_line_item_id: Optional[str] = None
    r"""Subscription line item ID"""

    subscription_id: Optional[str] = None
    r"""Subscription ID"""

    subscription_line_item: Optional[SubscriptionSubscriptionLineItem] = None

    subtotal: Optional[str] = None

    total_cost: Optional[str] = None
    r"""TotalCost is the final cost after discount (Subtotal - TotalDiscount)"""

    total_discount: Optional[str] = None

    total_usage: Optional[str] = None

    total_usage_display: Optional[str] = None
    r"""Empty string when feature has no reporting unit; otherwise the value in reporting units"""

    unit: Optional[str] = None

    unit_plural: Optional[str] = None

    window_size: Optional[WindowSize] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "add_on_id",
                "addon",
                "aggregation_type",
                "bucket_summaries",
                "commitment_info",
                "currency",
                "event_count",
                "event_name",
                "feature",
                "feature_id",
                "group",
                "meter",
                "meter_id",
                "name",
                "plan",
                "plan_id",
                "points",
                "price",
                "price_id",
                "properties",
                "reporting_unit",
                "source",
                "sources",
                "sub_line_item_id",
                "subscription_id",
                "subscription_line_item",
                "subtotal",
                "total_cost",
                "total_discount",
                "total_usage",
                "total_usage_display",
                "unit",
                "unit_plural",
                "window_size",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
