"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .analytics_viewdefinition import (
    AnalyticsViewDefinition,
    AnalyticsViewDefinitionTypedDict,
)
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ViewResponseTypedDict(TypedDict):
    definition: NotRequired[AnalyticsViewDefinitionTypedDict]
    id: NotRequired[str]
    name: NotRequired[str]
    version: NotRequired[int]


class ViewResponse(BaseModel):
    definition: Optional[AnalyticsViewDefinition] = None

    id: Optional[str] = None

    name: Optional[str] = None

    version: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["definition", "id", "name", "version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
