"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tirdad_sdk.types import UnrecognizedStr
from typing import Literal, Union


WalletType = Union[
    Literal[
        "PRE_PAID",
        "POST_PAID",
    ],
    UnrecognizedStr,
]
