"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .checkoutaction import CheckoutAction
from .checkoutpaymentprovider import CheckoutPaymentProvider
from .checkoutstatus import CheckoutStatus
from .paymentaction import PaymentAction, PaymentActionTypedDict
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class WebhookDtoCheckoutSessionTypedDict(TypedDict):
    action: NotRequired[CheckoutAction]
    cancelled_at: NotRequired[datetime]
    checkout_invoice_id: NotRequired[str]
    checkout_payment_id: NotRequired[str]
    checkout_status: NotRequired[CheckoutStatus]
    completed_at: NotRequired[datetime]
    customer_id: NotRequired[str]
    expires_at: NotRequired[datetime]
    failure_reason: NotRequired[str]
    id: NotRequired[str]
    payment_action: NotRequired[PaymentActionTypedDict]
    payment_provider: NotRequired[CheckoutPaymentProvider]


class WebhookDtoCheckoutSession(BaseModel):
    action: Optional[CheckoutAction] = None

    cancelled_at: Optional[datetime] = None

    checkout_invoice_id: Optional[str] = None

    checkout_payment_id: Optional[str] = None

    checkout_status: Optional[CheckoutStatus] = None

    completed_at: Optional[datetime] = None

    customer_id: Optional[str] = None

    expires_at: Optional[datetime] = None

    failure_reason: Optional[str] = None

    id: Optional[str] = None

    payment_action: Optional[PaymentAction] = None

    payment_provider: Optional[CheckoutPaymentProvider] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "action",
                "cancelled_at",
                "checkout_invoice_id",
                "checkout_payment_id",
                "checkout_status",
                "completed_at",
                "customer_id",
                "expires_at",
                "failure_reason",
                "id",
                "payment_action",
                "payment_provider",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
