"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subscriptionphaseresponse import (
    SubscriptionPhaseResponse,
    SubscriptionPhaseResponseTypedDict,
)
from .webhookeventname import WebhookEventName
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class WebhookDtoSubscriptionPhaseWebhookPayloadTypedDict(TypedDict):
    event_type: NotRequired[WebhookEventName]
    phase: NotRequired[SubscriptionPhaseResponseTypedDict]


class WebhookDtoSubscriptionPhaseWebhookPayload(BaseModel):
    event_type: Optional[WebhookEventName] = None

    phase: Optional[SubscriptionPhaseResponse] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["event_type", "phase"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
