"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class WebhookDtoCouponAssociationTypedDict(TypedDict):
    coupon_id: NotRequired[str]
    end_date: NotRequired[datetime]
    id: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    start_date: NotRequired[datetime]
    subscription_id: NotRequired[str]
    subscription_line_item_id: NotRequired[str]


class WebhookDtoCouponAssociation(BaseModel):
    coupon_id: Optional[str] = None

    end_date: Optional[datetime] = None

    id: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None

    start_date: Optional[datetime] = None

    subscription_id: Optional[str] = None

    subscription_line_item_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "coupon_id",
                "end_date",
                "id",
                "metadata",
                "start_date",
                "subscription_id",
                "subscription_line_item_id",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
