"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .billingcadence import BillingCadence
from .billingperiod import BillingPeriod
from .pausestatus import PauseStatus
from .subscriptionstatus import SubscriptionStatus
from .subscriptiontype import SubscriptionType
from .webhookdto_customer import WebhookDtoCustomer, WebhookDtoCustomerTypedDict
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class WebhookDtoSubscriptionTypedDict(TypedDict):
    billing_cadence: NotRequired[BillingCadence]
    billing_period: NotRequired[BillingPeriod]
    billing_period_count: NotRequired[int]
    cancel_at: NotRequired[datetime]
    cancel_at_period_end: NotRequired[bool]
    cancelled_at: NotRequired[datetime]
    currency: NotRequired[str]
    current_period_end: NotRequired[datetime]
    current_period_start: NotRequired[datetime]
    customer: NotRequired[WebhookDtoCustomerTypedDict]
    customer_id: NotRequired[str]
    end_date: NotRequired[datetime]
    id: NotRequired[str]
    lookup_key: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    parent_subscription_id: NotRequired[str]
    pause_status: NotRequired[PauseStatus]
    plan_id: NotRequired[str]
    start_date: NotRequired[datetime]
    subscription_status: NotRequired[SubscriptionStatus]
    subscription_type: NotRequired[SubscriptionType]
    trial_end: NotRequired[datetime]
    trial_start: NotRequired[datetime]


class WebhookDtoSubscription(BaseModel):
    billing_cadence: Optional[BillingCadence] = None

    billing_period: Optional[BillingPeriod] = None

    billing_period_count: Optional[int] = None

    cancel_at: Optional[datetime] = None

    cancel_at_period_end: Optional[bool] = None

    cancelled_at: Optional[datetime] = None

    currency: Optional[str] = None

    current_period_end: Optional[datetime] = None

    current_period_start: Optional[datetime] = None

    customer: Optional[WebhookDtoCustomer] = None

    customer_id: Optional[str] = None

    end_date: Optional[datetime] = None

    id: Optional[str] = None

    lookup_key: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None

    parent_subscription_id: Optional[str] = None

    pause_status: Optional[PauseStatus] = None

    plan_id: Optional[str] = None

    start_date: Optional[datetime] = None

    subscription_status: Optional[SubscriptionStatus] = None

    subscription_type: Optional[SubscriptionType] = None

    trial_end: Optional[datetime] = None

    trial_start: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "billing_cadence",
                "billing_period",
                "billing_period_count",
                "cancel_at",
                "cancel_at_period_end",
                "cancelled_at",
                "currency",
                "current_period_end",
                "current_period_start",
                "customer",
                "customer_id",
                "end_date",
                "id",
                "lookup_key",
                "metadata",
                "parent_subscription_id",
                "pause_status",
                "plan_id",
                "start_date",
                "subscription_status",
                "subscription_type",
                "trial_end",
                "trial_start",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
