"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .billingperiod import BillingPeriod
from .invoicecadence import InvoiceCadence
from .pricetype import PriceType
from .subscriptionlineitementitytype import SubscriptionLineItemEntityType
from .webhookdto_price import WebhookDtoPrice, WebhookDtoPriceTypedDict
from datetime import datetime
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class WebhookDtoSubscriptionLineItemTypedDict(TypedDict):
    billing_period: NotRequired[BillingPeriod]
    billing_period_count: NotRequired[int]
    currency: NotRequired[str]
    display_name: NotRequired[str]
    end_date: NotRequired[datetime]
    entity_id: NotRequired[str]
    entity_type: NotRequired[SubscriptionLineItemEntityType]
    id: NotRequired[str]
    invoice_cadence: NotRequired[InvoiceCadence]
    metadata: NotRequired[Dict[str, str]]
    meter_display_name: NotRequired[str]
    meter_id: NotRequired[str]
    plan_display_name: NotRequired[str]
    price: NotRequired[WebhookDtoPriceTypedDict]
    price_id: NotRequired[str]
    price_type: NotRequired[PriceType]
    price_unit: NotRequired[str]
    quantity: NotRequired[str]
    start_date: NotRequired[datetime]
    subscription_id: NotRequired[str]


class WebhookDtoSubscriptionLineItem(BaseModel):
    billing_period: Optional[BillingPeriod] = None

    billing_period_count: Optional[int] = None

    currency: Optional[str] = None

    display_name: Optional[str] = None

    end_date: Optional[datetime] = None

    entity_id: Optional[str] = None

    entity_type: Optional[SubscriptionLineItemEntityType] = None

    id: Optional[str] = None

    invoice_cadence: Optional[InvoiceCadence] = None

    metadata: Optional[Dict[str, str]] = None

    meter_display_name: Optional[str] = None

    meter_id: Optional[str] = None

    plan_display_name: Optional[str] = None

    price: Optional[WebhookDtoPrice] = None

    price_id: Optional[str] = None

    price_type: Optional[PriceType] = None

    price_unit: Optional[str] = None

    quantity: Optional[str] = None

    start_date: Optional[datetime] = None

    subscription_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "billing_period",
                "billing_period_count",
                "currency",
                "display_name",
                "end_date",
                "entity_id",
                "entity_type",
                "id",
                "invoice_cadence",
                "metadata",
                "meter_display_name",
                "meter_id",
                "plan_display_name",
                "price",
                "price_id",
                "price_type",
                "price_unit",
                "quantity",
                "start_date",
                "subscription_id",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
