"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .meter_aggregation import MeterAggregation, MeterAggregationTypedDict
from .resetusage import ResetUsage
from pydantic import model_serializer
from tirdad_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class WebhookDtoMeterTypedDict(TypedDict):
    aggregation: NotRequired[MeterAggregationTypedDict]
    event_name: NotRequired[str]
    id: NotRequired[str]
    name: NotRequired[str]
    reset_usage: NotRequired[ResetUsage]


class WebhookDtoMeter(BaseModel):
    aggregation: Optional[MeterAggregation] = None

    event_name: Optional[str] = None

    id: Optional[str] = None

    name: Optional[str] = None

    reset_usage: Optional[ResetUsage] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["aggregation", "event_name", "id", "name", "reset_usage"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
