"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tirdad_sdk.types import UnrecognizedStr
from typing import Literal, Union


WindowSize = Union[
    Literal[
        "MINUTE",
        "15MIN",
        "30MIN",
        "HOUR",
        "3HOUR",
        "6HOUR",
        "12HOUR",
        "DAY",
        "WEEK",
        "MONTH",
    ],
    UnrecognizedStr,
]
