"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "tirdad-sdk"
__version__: str = "2.1.23"
__openapi_doc_version__: str = "1.0"
__gen_version__: str = "2.926.8"
__user_agent__: str = "speakeasy-sdk/python 2.1.23 2.926.8 1.0 tirdad-sdk"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
