"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
import httpx
import importlib
import sys
from tirdad_sdk import models, utils
from tirdad_sdk._hooks import SDKHooks
from tirdad_sdk.types import OptionalNullable, UNSET
from typing import Any, Callable, Dict, Optional, TYPE_CHECKING, Union, cast
import weakref

if TYPE_CHECKING:
    from tirdad_sdk.addons import Addons
    from tirdad_sdk.alerts import Alerts
    from tirdad_sdk.alertsettings import AlertSettings
    from tirdad_sdk.checkout import Checkout
    from tirdad_sdk.costs import Costs
    from tirdad_sdk.coupon_associations import CouponAssociations
    from tirdad_sdk.coupons import Coupons
    from tirdad_sdk.credit_grants import CreditGrants
    from tirdad_sdk.credit_notes import CreditNotes
    from tirdad_sdk.customers import Customers
    from tirdad_sdk.entitlements import Entitlements
    from tirdad_sdk.environments import Environments
    from tirdad_sdk.events import Events
    from tirdad_sdk.features import Features
    from tirdad_sdk.groups import Groups
    from tirdad_sdk.integrations import Integrations
    from tirdad_sdk.invoices import Invoices
    from tirdad_sdk.payments import Payments
    from tirdad_sdk.plans import Plans
    from tirdad_sdk.price_units import PriceUnits
    from tirdad_sdk.prices import Prices
    from tirdad_sdk.rbac import Rbac
    from tirdad_sdk.scheduled_tasks import ScheduledTasks
    from tirdad_sdk.secrets import Secrets
    from tirdad_sdk.subscriptions import Subscriptions
    from tirdad_sdk.tasks import Tasks
    from tirdad_sdk.tax_associations import TaxAssociations
    from tirdad_sdk.tax_rates import TaxRates
    from tirdad_sdk.tenants import Tenants
    from tirdad_sdk.users import Users
    from tirdad_sdk.wallets import Wallets
    from tirdad_sdk.webhook_events import WebhookEvents
    from tirdad_sdk.workflows import Workflows


class Tirdad(BaseSDK):
    r"""Flexprice API: Flexprice API Service"""

    addons: "Addons"
    credit_grants: "CreditGrants"
    entitlements: "Entitlements"
    alerts: "Alerts"
    alert_settings: "AlertSettings"
    checkout: "Checkout"
    costs: "Costs"
    coupons: "Coupons"
    coupon_associations: "CouponAssociations"
    credit_notes: "CreditNotes"
    customers: "Customers"
    wallets: "Wallets"
    invoices: "Invoices"
    environments: "Environments"
    events: "Events"
    features: "Features"
    groups: "Groups"
    integrations: "Integrations"
    payments: "Payments"
    plans: "Plans"
    prices: "Prices"
    price_units: "PriceUnits"
    rbac: "Rbac"
    secrets: "Secrets"
    subscriptions: "Subscriptions"
    tasks: "Tasks"
    scheduled_tasks: "ScheduledTasks"
    tax_associations: "TaxAssociations"
    tax_rates: "TaxRates"
    tenants: "Tenants"
    users: "Users"
    webhook_events: "WebhookEvents"
    workflows: "Workflows"
    _sub_sdk_map = {
        "addons": ("tirdad_sdk.addons", "Addons"),
        "credit_grants": ("tirdad_sdk.credit_grants", "CreditGrants"),
        "entitlements": ("tirdad_sdk.entitlements", "Entitlements"),
        "alerts": ("tirdad_sdk.alerts", "Alerts"),
        "alert_settings": ("tirdad_sdk.alertsettings", "AlertSettings"),
        "checkout": ("tirdad_sdk.checkout", "Checkout"),
        "costs": ("tirdad_sdk.costs", "Costs"),
        "coupons": ("tirdad_sdk.coupons", "Coupons"),
        "coupon_associations": ("tirdad_sdk.coupon_associations", "CouponAssociations"),
        "credit_notes": ("tirdad_sdk.credit_notes", "CreditNotes"),
        "customers": ("tirdad_sdk.customers", "Customers"),
        "wallets": ("tirdad_sdk.wallets", "Wallets"),
        "invoices": ("tirdad_sdk.invoices", "Invoices"),
        "environments": ("tirdad_sdk.environments", "Environments"),
        "events": ("tirdad_sdk.events", "Events"),
        "features": ("tirdad_sdk.features", "Features"),
        "groups": ("tirdad_sdk.groups", "Groups"),
        "integrations": ("tirdad_sdk.integrations", "Integrations"),
        "payments": ("tirdad_sdk.payments", "Payments"),
        "plans": ("tirdad_sdk.plans", "Plans"),
        "prices": ("tirdad_sdk.prices", "Prices"),
        "price_units": ("tirdad_sdk.price_units", "PriceUnits"),
        "rbac": ("tirdad_sdk.rbac", "Rbac"),
        "secrets": ("tirdad_sdk.secrets", "Secrets"),
        "subscriptions": ("tirdad_sdk.subscriptions", "Subscriptions"),
        "tasks": ("tirdad_sdk.tasks", "Tasks"),
        "scheduled_tasks": ("tirdad_sdk.scheduled_tasks", "ScheduledTasks"),
        "tax_associations": ("tirdad_sdk.tax_associations", "TaxAssociations"),
        "tax_rates": ("tirdad_sdk.tax_rates", "TaxRates"),
        "tenants": ("tirdad_sdk.tenants", "Tenants"),
        "users": ("tirdad_sdk.users", "Users"),
        "webhook_events": ("tirdad_sdk.webhook_events", "WebhookEvents"),
        "workflows": ("tirdad_sdk.workflows", "Workflows"),
    }

    def __init__(
        self,
        api_key_auth: Union[str, Callable[[], str]],
        server_idx: Optional[int] = None,
        url_params: Optional[Dict[str, str]] = None,
        server_url: Optional[str] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param api_key_auth: The api_key_auth required for authentication
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        client_supplied = True
        if client is None:
            client = httpx.Client(follow_redirects=True)
            client_supplied = False

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient(follow_redirects=True)
            async_client_supplied = False

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        security: Any = None
        if api_key_auth is None:
            security = None
        elif callable(api_key_auth):
            # pylint: disable=unnecessary-lambda-assignment
            security = lambda: models.Security(api_key_auth=api_key_auth())
        else:
            security = models.Security(api_key_auth=api_key_auth)

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
            parent_ref=self,
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    def dynamic_import(self, modname, retries=3):
        for attempt in range(retries):
            try:
                return importlib.import_module(modname)
            except KeyError:
                # Clear any half-initialized module and retry
                sys.modules.pop(modname, None)
                if attempt == retries - 1:
                    break
        raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = self.dynamic_import(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration, parent_ref=self)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None
